# Generated by Django 4.1.4 on 2022-12-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='img',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
